# Generated by Django 3.2.15 on 2022-09-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='none',
            new_name='done',
        ),
    ]
